//########## EC2CREDENTIALS #########
export const REQUEST_EC2CREDENTIALS = "REQUEST_EC2CREDENTIALS";
export const RECEIVE_EC2CREDENTIALS = "RECEIVE_EVENTS";
export const REQUEST_EC2CREDENTIALS_FAILURE = "REQUEST_EC2CREDENTIALS_FAILURE";
export const REQUEST_EC2CREDENTIAL_DETAILS = "REQUEST_EC2CREDENTIAL_DETAILS";
export const REQUEST_EC2CREDENTIAL_DETAILS_FAILURE =
  "REQUEST_EC2CREDENTIAL_DETAILS_FAILURE";
export const RECEIVE_EC2CREDENTIAL_DETAILS = "RECEIVE_EC2CREDENTIAL_DETAILS";
